### ISSUE TITLE
Fix crash in Firefox

### ISSUE THREAD

**Issue by davidlougheed** [patacat/patacat#17]
Error:

```
IndexSizeError: Index or size is negative or greater than the allowed amount
```

**Comment by AllanWang** [comment]
Where is this coming from?

**Comment by davidlougheed** [comment]
Cat.js drawing

**Comment by davidlougheed** [comment]
line 95

**Comment by AllanWang** [comment]
https://github.com/patacat/patacat/blob/fb537c139320740f90e1fdea37dd91df18eb5c72/js_david/Cat.js#L92-L100

There? Please link if it's not this commit

**Comment by davidlougheed** [comment]
😠
